### ISSUE TITLE
`generate_rust` fails in GitHub Actions with `io error`

### ISSUE THREAD

**Issue by 617a7a** [planus-org/planus#171]
Having issues with a GH Action running Planus. It installs with Cargo. `planus check` runs okay.

<img width="780" alt="Screenshot 2023-01-29 at 12 04 20" src="https://user-images.githubusercontent.com/67651251/215324884-0500bf08-35e1-4b76-b21f-57f31b6c2dd6.png">

It's failing somewhere in here:
https://github.com/planus-org/planus/blob/be40ee01b76ebd61daea155a1a78d618ba4b8588/crates/planus-codegen/src/lib.rs#L30

**Comment by TethysSvensson** [comment]
I am not sure if we have enough context to diagnose this. Can you run it with `RUST_BACKTRACE=1` as suggested?

**Comment by 617a7a** [comment]
![image](https://user-images.githubusercontent.com/67651251/216649107-4b75b9fb-c0ce-4c80-96f6-4929327b96fd.jpeg)

**Comment by TethysSvensson** [comment]
This is definitely a bug in terms of error reporting on our side.

I think the underlying issue might be that you do not have rustfmt installed in the CI environment. Could you verify whether that is the case?

**Comment by 617a7a** [comment]
Can confirm that it was because `rustfmt` wasn't installed. All working now. We can open a new issue and reference this to fix the error reporting here.
