### ISSUE TITLE
Error: Doc comments are not meaningful here.

### ISSUE THREAD

**Issue by ritchie46** [planus-org/planus#215]
I am trying to compile the flatbufffers from the arrow project, but I get these errors:

https://github.com/apache/arrow/tree/main/format

```
error: Doc comments are not meaningful here.
   ┌─ Tensor.fbs:19:1
   │
19 │ /// "ndarrays". Arrow implementations in general are not required to implement
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Is there a way to ignore the comments?

**Comment by TethysSvensson** [comment]
Not currently, but I have implemented a PR to do this.

**Comment by TethysSvensson** [comment]
This is done as of #216.
