### ISSUE TITLE
Support strings and structs in unions

### ISSUE THREAD

**Issue by TheButlah** [planus-org/planus#96]
I think in the main flatc, Rust is the only language that doesn't allow structs in unions. It would be truly a life saver if it could be implemented in here. 

I also noticed that strings weren't currently supported.

If you have guidance on how to do this, and think it would be feasible for someone with no prior knowledge of how flatbuffers is implemented lmk 😢

**Comment by TethysSvensson** [comment]
We have added support for strings in unions in #97. Adding support for structs in unions is a bit more work, but we'll see if we can make it happen.
